apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: celery
  name: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: celery
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: celery
    spec:
      containers:
        - args:
            - celery
            - -A
            - RATypeInfer
            - worker
            - --loglevel=info
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"              
          image: backend:latest
          imagePullPolicy: Never
          name: celery
          volumeMounts:
          - mountPath: /app/media  # Path inside the container
            name: app-data
      restartPolicy: Always

      volumes:
        - name: app-data
          hostPath:
            path: /app/media  # Path on the host
            type: DirectoryOrCreate