version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./Frontend/data-inference-app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - CHOKIDAR_USEPOLLING=true # Required for hot-reloading in some environments
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/frontend

  backend:
    container_name: backend
    build:
      context: ./Backend/RATypeInfer
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
    volumes:
      - ./backend:/backend

networks:
  app-network:
    driver: bridge
