apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: backend
  name: backend
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"
spec:
  type: LoadBalancer 
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: backend
