apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: celery-scaler-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: celery-scaler
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
